### ISSUE TITLE
Error compiling with Node 4

### ISSUE THREAD

**Issue by oji** [gitterHQ/request-http-cache#1]
I'm trying to install this module on a node 4 project, but it's failing. It's complaining with protobuf module, maybe it needs updating? 

gyp: /root/.node-gyp/4.2.1/common.gypi not found (cwd: /opt/package/node_modules/request-http-cache/node_modules/snappy) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/package/node_modules/request-http-cache/node_modules/snappy/node_modules/pangyp/lib/configure.js:346:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.5-12.1.x86_64
gyp ERR! command "/usr/bin/node" "/opt/package/node_modules/request-http-cache/node_modules/snappy/node_modules/.bin/pangyp" "rebuild"
gyp ERR! cwd /opt/package/node_modules/request-http-cache/node_modules/snappy
gyp ERR! node -v v4.2.1
gyp ERR! pangyp -v v2.3.2
gyp ERR! not ok
npm ERR! Linux 3.10.5-12.1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "request-http-cache"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! protobuf@0.11.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the protobuf@0.11.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the protobuf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls protobuf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/package/npm-debug.log

**Comment by suprememoocow** [comment]
`request-http-cache` had a dependency on `protobuf` (and `snappy`), which allowed protobuffers to be used as an alternative serializer and snappy as an optional compression library. In practice though, they both slow things down more than speed things up, which was the intention.

Unfortunately the `protobuf` library doesn't compile in node 4, so I've moved into a separate module. Version `1.0.0` fixes this issue.
